version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: jj_postgres
    environment:
      POSTGRES_USER: jj
      POSTGRES_PASSWORD: jj
      POSTGRES_DB: jj
    ports:
      - "5432:5432"
    volumes:
      - jj_pgdata:/var/lib/postgresql/data
volumes:
  jj_pgdata:
